### ISSUE TITLE
Wrong firmware loaded? 65535

### ISSUE THREAD

**Issue by el-samiyel** [adafruit/Adafruit-I2C-QT-Rotary-Encoder-PCB#1]
hi,

Tried running your example code but getting this error:

Wrong firmware loaded? 65535

Can anybody help?

**Comment by caternuson** [comment]
Looks like this was resolved?
https://github.com/adafruit/Adafruit_Seesaw/issues/77#issuecomment-1212418924

Closing since this is the repo for the hardware.

Also suggest posting in the forums with any general "not working" issues before opening a repo issue.
https://forums.adafruit.com/
